### PR TITLE
Notes for linux users

### PR DESCRIPTION
**Pull request by Mte90**
Just a line with the linux command :-)

### CODE REVIEW

**Review by matheusmoreira — CHANGES_REQUESTED** [review]
List items 4 and 5 were needlessly renumbered to 5 and 6, resulting in a disconnected list where 4 is skipped.

**Comment by Mte90** [comment]
It is rendered in this way:
immagine

**Comment by matheusmoreira** [comment]
The markdown parser is smart enough to figure out what you mean but it's still weird for anyone reading the markup.

**Comment by Mte90** [comment]
ping

**Comment by Mte90** [comment]
ping

**Comment by Mte90** [comment]
ping

**Pull request closed without merging**
