### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by milroneth**
Fixed NMS version from 1.09 to 2.09

### CODE REVIEW

**Comment by Purg25** [comment]
so when is ver 2.2 going to be added?

**Comment by goatfungus** [comment]
CHANGELOG.md gets updated with every changed version.

**Comment by milroneth** [comment]
> CHANGELOG.md gets updated with every changed version.

Of course it is. This was a commit to fix a typo in an the changelog when it was still relevant (It was just released).

Apparently you didn't notice it before and of course it would be too late to merge now, but if you could correct it manually, it would be nice. As seen in the commit, it's under 1.6.3 where it should say `database for NMS 2.09`

**Comment by Purg25** [comment]
Why am I being included in this email?

**Comment by milroneth** [comment]
> Why am I being included in this email?
Because you ignorantly commented "so when is ver 2.2 going to be added?" on a completely irrelevant GitHub merge request.

Please don't reply to the email again, as that automatically creates more comments on said GitHub thread, instead find the unsubscribe link inside it and click that. In the future refrain from posting irrelevant questions in random places and please, don't ever again ask "when x ready" for software you are not paying for but people provide you for free, it's rude at the very least.

**Comment by Purg25** [comment]
ok kid. I give no fucks about rudeness at this point. i asked you why i was
included in that fucking email. you coming back at me with that response
was "Rude" a simple sorry or my bad would have been quicker. Telling a
person Not to write back is Rude. Going further about the whole not asking
questions is Rude. I didn't ask shit about the software, did i. No i don't
need to remove my email from the list you have that ability i don't have to
go looking for a fucking unsubscribe since YOU never even told me where the
fuck to look for it in the first place. Now be a Good Little Kid and shut
your fucking mouth. cause i wasn't talking about the "Software"

**Comment by milroneth** [comment]
> Apparently you didn't notice it before and of course it would be too late to merge now, but if you could correct it manually, it would be nice. As seen in the commit, it's under 1.6.3 where it should say `database for NMS 2.09`

Hey, @goatfungus, any chance of doing that edit? It's still wrong and some people still need older versions as they like playing with older versions of the game and this is confusing. It's a simple typo, but it would help if it got fixed. Thank you.

**Pull request closed without merging**
